from pathlib import Path

AQUACROP_VERSION = "7.1"
ROOT_DIR: Path = Path(__file__).resolve().parent.parent
DATA_DIR: Path = ROOT_DIR / "data"
EXTERNAL_DIR: Path = DATA_DIR / "external"
INTERIM_DIR: Path = DATA_DIR / "interim"
RAW_DIR: Path = DATA_DIR / "raw"
PROCESSED_DIR: Path = DATA_DIR / "processed"
EXTERNAL_CLIMATE_DIR: Path = EXTERNAL_DIR / "climate"
INTERIM_CLIMATE_DIR: Path = INTERIM_DIR / "climate"
EXTERNAL_MAPDATA_DIR: Path = EXTERNAL_DIR / "mapdata"
INTERIM_MAPDATA_DIR: Path = INTERIM_DIR / "mapdata"
RAW_YIELD_DIR: Path = RAW_DIR / "yield"
INTERIM_YIELD_DIR: Path = INTERIM_DIR / "yield"
CO2_DIR: Path = EXTERNAL_DIR / "co2"
RAW_WEATHER_DIR = RAW_DIR / "weather"
PROCESSED_WEATHER_DIR = PROCESSED_DIR / "weather"
MODELS_DIR = ROOT_DIR / "models"
CO2_PROCESSED_DIR = PROCESSED_DIR / "co2"
PROCESSED_CLIMATE_DIR = PROCESSED_DIR / "climate"
RESULTS_DIR = ROOT_DIR / "results"
FIGURES_DIR = RESULTS_DIR / "figures"
MODEL_RUNNING_DIR = Path("E:") / "aquacrop"
#MODEL_RUNNING_DIR = ROOT_DIR / "models"